### ISSUE TITLE
Some issues and implementation details

### ISSUE THREAD

**Issue by magnetmoment** [yinjunbo/IS-Fusion#6]
Thank you very much for sharing your excellent work! I 'd like to record some implementation details.
1. Some files may be missing in mmdet3D/models. 
I've tried to supplement them with the files from the autoalignv2 project.

2. In mmdet3D/models./__init__.py, I had to delete line 20 (from .vtransforms import *) to make sure it can successfully run.

However, I still have some questions:
1. In the project, I can't find the Point-to-Grid Transformer module you've mentioned in your paper.
2. How can you get the checkpoint of the baseline Transfusion which can achieve 65.1mAP?  Did you train it from scratch?  The checkpoint (IS-Fusion_epoch_10.pth) you provided seems like final weights rather than a pre-trained model.

I'm sorry for taking up your time, and I hope to receive your reply.

**Comment by yinjunbo** [comment]
Thanks for pointing it out. It seems there was a mismatch between the remote codebase on my server. Hope you’ve fixed it right now. 
1. We have identified that the Point-to-Grid Transformer consumes excessive memory, making it unsuitable for V100 GPUs. Therefore, we have removed it from the released version to ensure smooth operation on commonly used V100 GPUs. It's worth noting that in the original paper, we utilized 8*A100 (80G) GPUs for optimal performance. 
2. The reported performance of 65.1 mAP for Transfusion-L was achieved by removing the image modality. Since IS-Fusion primarily focuses on multimodal implementation, we have excluded this step from the released version. However, you can easily achieve it by removing the image input.
If you encounter any further issues or have additional questions, please don't hesitate to let me know. Thanks.

**Comment by wyf0414** [comment]
@yinjunbo 
Hi, will the deletion of the Point to Grid Transformer module affect the final performance?
I am trainning the model, worrying that can't meet your proposed performance.
